name: Build and Deploy
on: 
  push:
    branches:
      - "main"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2

      - name: Install and Build
        run: |
          npm ci
          npm run build
      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: gh_pages
          folder: dist